[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-building-blocks"
version = "0.1.0"
description = "Cisco AI Building Blocks (DB + Agent combined)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sqlalchemy>=1.4",
    "psycopg2-binary",
    "rich>=14.0.0",
    "colorama",
]

[project.scripts]
create-platform                = "user_commands.create_platform:main"
create-platform-index          = "user_commands.create_platform_index:main"
create-sdk                     = "user_commands.create_sdk:main"
reset-platform                 = "user_commands.reset_platform:main"
create-domain-demo-index       = "user_commands.create_domain_demo_index:main"
generate-openapi-sdks          = "user_commands.generate_openapi_sdks:main"
menu                           = "user_commands.command_menu:main"
delete-sdk                     = "user_commands.delete_sdk:main"
delete-platform                = "user_commands.reset_platform:main"
serve-app                      = "app.main:main"
create-index                   = "db_scripts.create_index:main"
create-platform-db             = "db_scripts.create_platform:main"
generate-openapi-sdks-db       = "db_scripts.generate_openapi_sdks:main"

[tool.setuptools.packages.find]
where   = ["src"]
include = ["db_scripts*", "user_commands*", "app*", "app_scripts*"]
