# docker/docker-compose.yaml

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      #- --enable-feature=remote-write-receiver
      - --web.enable-remote-write-receiver 
      - --enable-feature=exemplar-storage
    ports:
      # Expose only to 127.0.0.1 so it’s reachable by host-side Nginx
      - "127.0.0.1:9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"   # let Prometheus scrape FastAPI

  tempo:
    image: grafana/tempo:2.7.1
    container_name: tempo
    command:
      - --config.file=/etc/tempo/tempo.yaml
    volumes:
      - ./tempo.yaml:/etc/tempo/tempo.yaml:ro
      - tempo-data:/var/tempo
    ports:
      - "127.0.0.1:3200:3200"  # Tempo HTTP / query / metrics
      - "127.0.0.1:4318:4318"  # OTLP/HTTP ingest
      # - "127.0.0.1:4317:4317"  # OTLP/gRPC (optional)

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=cisco101
    volumes:
      - grafana-data:/var/lib/grafana                     # DB
      - ./provisioning/datasources.yaml:/etc/grafana/provisioning/datasources/ds.yaml:ro
    depends_on:
      - prometheus
      - tempo
    ports:
      - "127.0.0.1:3000:3000"



volumes:
  tempo-data:
  grafana-data: