#docker/grafana-datasources.yml
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    version: 1

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    version: 1
