global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # Scrape FastAPI application metrics
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']

  # (Optional) Scrape Prometheus itself for metrics 
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
